import = [
	"~/.dotfiles/alacritty/themes/catppuccin-mocha.toml"
]

[shell]
program = "/opt/homebrew/bin/tmux"

[font]

normal = { family = "Jetbrains Mono" }
size = 15

[window]

padding = { x = 10, y = 10 }
