general.import = [
	"~/alacritty-theme/themes/gruvbox_hard.toml"
]

# terminal.shell = "/bin/zsh"
# terminal.program = "tmux"
[terminal.shell]
program = "/usr/local/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[font]

normal = { family = "JetbrainsMono Nerd Font" }
size = 15
offset.y = 5

[window]

padding = { x = 10, y = 10 }
