#!/usr/bin/env python3

import argparse
import subprocess

def exec(cmd):
	proc = subprocess.Popen(cmd, shell=True, text=True)
	proc.communicate()

def make_parser():
    parser = argparse.ArgumentParser(
        prog='ld', 
        description='Common linode dev commands'
    )
    
    subparsers = parser.add_subparsers(
        dest='command', 
        help='Available subcommands'
    )
    
    ## Query ##

    parser_db = subparsers.add_parser('db', help='Execute a db command')
    parser_db.add_argument('query', help='The db command to execute')
    

    ## Start Env ##

    subparsers.add_parser('start', help='Start the env')
    
    ## Tail Logs ##

    parser_logs = subparsers.add_parser('logs', help='Tail logs for a container')
    parser_logs.add_argument('container',       help='The container to view logs for')


    ## Attach to Bash ##

    parser_attach = subparsers.add_parser('attach', help='Attach to a container')
    parser_attach.add_argument('container',         help='The container to attach to')

    ## Execute a Bash Command ##

    parser_attach = subparsers.add_parser('exec', help='Execute a bash command in a container')
    parser_attach.add_argument('container',       help='The container to exec in')
    parser_attach.add_argument('cmd',             help='The command to run')

    return parser

def cmd_db(args):
    exec(f"docker compose exec -it db mysql hosting --user=root --password=r1r1r1 -P 5033 --silent --execute '{args.query}'")

def cmd_start():
    exec("~/cometlab-setup/start.sh")

def cmd_attach(args):
    exec(f"docker exec -it {args.container} bash")

def cmd_exec(args):
    exec(f"docker exec {args.container} {args.cmd}")

def cmd_logs(args):
    print(f"TODO {args.container}")

def main():
    parser = make_parser()
    
    args = parser.parse_args()
    
    if   args.command == 'db':
        cmd_db(args)
    elif args.command == 'start':
        cmd_start()
    elif args.command == 'attach':
        cmd_attach(args)
    elif args.command == 'exec':
        cmd_exec(args)
    elif args.command == 'logs':
        cmd_logs(args)
    else:
        parser.print_help()

if __name__ == '__main__':
    main()

